import { LuCable, LuSofa } from 'react-icons/lu';
import { PiPlantLight, PiTShirtLight } from 'react-icons/pi';
import { AiOutlineHome } from 'react-icons/ai';
import { RiCarLine } from 'react-icons/ri';
import { BiDumbbell } from 'react-icons/bi';
import { IoBagOutline } from 'react-icons/io5';

export const catalogue = [
  {
    name: 'Elektronika',
    icon: 'LuCable',
  },
  {
    name: 'Mebel',
    icon: 'LuSofa',
  },
  {
    name: 'Ev və bağ',
    icon: 'PiPlantLight',
  },
  {
    name: 'Daşınmaz əmlak',
    icon: 'AiOutlineHome',
  },
  {
    name: 'Nəqliyyat',
    icon: 'RiCarLine',
  },
  {
    name: 'İdman və hobbi',
    icon: 'BiDumbbell',
  },
  {
    name: 'Şəxsi əşyalar',
    icon: 'PiTShirtLight',
  },
  {
    name: 'İş',
    icon: 'IoBagOutline',
  },
  {
    name: 'Xidmətlər',
    icon: null,
  },
  {
    name: 'Heyvanlar',
    icon: null,
  },
  {
    name: 'Biznes üçün avadanlıq',
    icon: null,
  },
  {
    name: 'Uşaq dünyası',
    icon: null,
  },
  {
    name: 'Tibbi məhsullar',
    icon: null,
  },
];

export const cities = [
  'Bakı',
  'Ağdam',
  'Ağdaş',
  'Ağcabədi',
  'Ağstafa',
  'Ağsu',
  'Astara',
  'Babək',
  'Balakən',
  'Bərdə',
  'Beyləqan',
  'Biləsuvar',
  'Cəbrayıl',
  'Cəlilabad',
  'Culfa',
  'Daşkəsən',
  'Füzuli',
  'Gədəbəy',
  'Goranboy',
  'Göyçay',
  'Göygöl',
  'Hacıqabul',
  'Xaçmaz',
  'Xızı',
  'Xocalı',
  'Xocavənd',
  'İmişli',
  'İsmayıllı',
  'Kəlbəcər',
  'Kəngərli',
  'Kürdəmir',
  'Qəbələ',
  'Qax',
  'Qazax',
  'Qobustan',
  'Quba',
  'Qubadlı',
  'Qusar',
  'Laçın',
  'Lənkəran',
  'Lerik',
  'Masallı',
  'Neftçala',
  'Oğuz',
  'Ordubad',
  'Saatlı',
  'Sabirabad',
  'Sədərək',
  'Salyan',
  'Samux',
  'Şabran',
  'Şahbuz',
  'Şəki',
  'Şamaxı',
  'Şəmkir',
  'Şərur',
  'Şuşa',
  'Siyəzən',
  'Tərtər',
  'Tovuz',
  'Ucar',
  'Yardımlı',
  'Yevlax',
  'Zəngilan',
  'Zaqatala',
  'Zərdab',
];
